server:
  port: 8082

spring:
  application:
    name: event-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/project_db
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-service-group
      auto-offset-reset: earliest

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

kafka:
  topics:
    checkin-events: checkin-events
    alert-events: alert-events
    escalation-events: escalation-events
    anomaly-events: anomaly-events
    health-journal-events: health-journal-events
    health-alert-events: health-alert-events
    care-visit-events: care-visit-events
    care-match-events: care-match-events

logging:
  level:
    com.project: DEBUG
